/*********************************************************************************************************************
* Filename		: conditionally-format-columns-rows-in-PROC-REPORT.sas
* programmer	: Chang
* purpose			: Conditionally format columns or rows for output table generated by PROC REPORT
* date created	: 20190311
* how to use 	: 
* note				: 
------------------------------------------------------------------------------------------------------------------------------
Date			Update
-------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------*/
%SYSMACDELETE color_columns;

/*Define the macro*/
%macro color_columns(column_names= /*Type names of variables to display in the color specified belows, separated by space*/
										,foreground_color= /*Type name of a color, not in quote*/
										);

%let n_var2format=%sysfunc(countw(&column_names.));
%do i=1 %to &n_var2format.;
  %let var_01 = %scan(&column_names., &i.);
  compute &var_01. ;
	/*_COL_ is the column that is associated with the COMPUTE block variable*/
		call define(_COL_, 'style', "style=[foreground= &foreground_color.]" ); /*foreground=blue */
  endcomp;
%end;

%mend color_columns;
